name: phasc
channels:
  - conda-forge
  - bioconda
  - nodefaults
dependencies:
  - python>=3.9,<3.13
  - cooler>=0.9
  - h5py
  - numpy
  - pandas
  - scipy
  - matplotlib
  - networkx>=3.0
  - networkit
  - pysam
  - chromap
  - hicexplorer
